version: "3.9"

services:
  web:
    container_name: web
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/web.dockerfile
    ports:
      - "80:5000"
    depends_on:
      mongo:
        condition: service_started
